red_dwarf_config:
  schema: foo
  table: bar
  unload_format: csv
  timestamp_column: created_at
  delete_after: false
  vacuum_after: false
  analyse_after: false
  days_to_keep: 365
  partition_by: created_at
  cast_partition_by_time: true
  s3_bucket: my-s3-bucket-goes-here
  s3_key: my-s3-key-goes-here

